name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly-2020-09-27
          target: wasm32-unknown-unknown
          override: true
          default: true
      - name: Install clippy
        run: rustup component add clippy
      - name: Run clippy
        run: cargo clippy --release -- -D warnings
      - name: Tests
        run: time cargo test --all --release --locked
      - name: Build release
        run: time cargo build --release 
